name: Build Native AOT

on:
  release:
    types: [published]

jobs:
  build_project:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            zip_name: Pokefight-Remastered-win-x64.zip
            publish_path: bin/Release/net9.0/win-x64/publish/
          - os: ubuntu-latest
            rid: linux-x64
            zip_name: Pokefight-Remastered-linux-x64.zip
            publish_path: bin/Release/net9.0/linux-x64/publish/
          - os: macos-latest
            rid: osx-x64
            zip_name: Pokefight-Remastered-osx-x64.zip
            publish_path: bin/Release/net9.0/osx-x64/publish/

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish for ${{ matrix.rid }}
        run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true/p:PublishAot=true

      - name: Zip and Upload to Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd ${{ github.workspace }}
          zip -r ${{ matrix.zip_name }} ${{ matrix.publish_path }}
          gh release upload ${{ github.event.release.tag_name }} ${{ matrix.zip_name }}
        shell: bash